give @s ghoulcraft:barstool1acacia
give @s ghoulcraft:barstool2acacia
give @s ghoulcraft:barstool3acacia
give @s ghoulcraft:barstool4acacia
give @s ghoulcraft:barstool1birch
give @s ghoulcraft:barstool2birch
give @s ghoulcraft:barstool3birch
give @s ghoulcraft:barstool4birch
give @s ghoulcraft:barstool1dark
give @s ghoulcraft:barstool2dark
give @s ghoulcraft:barstool3dark
give @s ghoulcraft:barstool4dark
give @s ghoulcraft:barstool1jungle
give @s ghoulcraft:barstool2jungle
give @s ghoulcraft:barstool3jungle
give @s ghoulcraft:barstool4jungle
give @s ghoulcraft:barstool1oak
give @s ghoulcraft:barstool2oak
give @s ghoulcraft:barstool3oak
give @s ghoulcraft:barstool4oak
give @s ghoulcraft:barstool1spruce
give @s ghoulcraft:barstool2spruce
give @s ghoulcraft:barstool3spruce
give @s ghoulcraft:barstool4spruce