gamerule sendcommandfeedback false
give @s ghoulcraft:canmatch_jungle_black
give @s ghoulcraft:canmatch_jungle_blue
give @s ghoulcraft:canmatch_jungle_brown
give @s ghoulcraft:canmatch_jungle_cyan
give @s ghoulcraft:canmatch_jungle_green
give @s ghoulcraft:canmatch_jungle_gray
give @s ghoulcraft:canmatch_jungle_light_blue
give @s ghoulcraft:canmatch_jungle_light_gray
give @s ghoulcraft:canmatch_jungle_lime
give @s ghoulcraft:canmatch_jungle_orange
give @s ghoulcraft:canmatch_jungle_magenta
give @s ghoulcraft:canmatch_jungle_pink
give @s ghoulcraft:canmatch_jungle_purple
give @s ghoulcraft:canmatch_jungle_red
give @s ghoulcraft:canmatch_jungle_white
give @s ghoulcraft:canmatch_jungle_yellow