gamerule sendcommandfeedback false
give @s ghoulcraft:chair1acacia
give @s ghoulcraft:chair2acacia
give @s ghoulcraft:chair3acacia
give @s ghoulcraft:chair4acacia
give @s ghoulcraft:chair1birch
give @s ghoulcraft:chair2birch
give @s ghoulcraft:chair3birch
give @s ghoulcraft:chair4birch
give @s ghoulcraft:chair1dark
give @s ghoulcraft:chair2dark
give @s ghoulcraft:chair3dark
give @s ghoulcraft:chair4dark
give @s ghoulcraft:chair1jungle
give @s ghoulcraft:chair2jungle
give @s ghoulcraft:chair3jungle
give @s ghoulcraft:chair4jungle
give @s ghoulcraft:chair1oak
give @s ghoulcraft:chair2oak
give @s ghoulcraft:chair3oak
give @s ghoulcraft:chair4oak
give @s ghoulcraft:chair1spruce
give @s ghoulcraft:chair2spruce
give @s ghoulcraft:chair3spruce
give @s ghoulcraft:chair4spruce