gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_left_black4
give @s ghoulcraft:sofa_left_blue4
give @s ghoulcraft:sofa_left_brown4
give @s ghoulcraft:sofa_left_cyan4
give @s ghoulcraft:sofa_left_green4
give @s ghoulcraft:sofa_left_gray4
give @s ghoulcraft:sofa_left_lblue4
give @s ghoulcraft:sofa_left_lgray4
give @s ghoulcraft:sofa_left_lime4
give @s ghoulcraft:sofa_left_orange4
give @s ghoulcraft:sofa_left_magenta4
give @s ghoulcraft:sofa_left_pink4
give @s ghoulcraft:sofa_left_purple4
give @s ghoulcraft:sofa_left_red4
give @s ghoulcraft:sofa_left_white4
give @s ghoulcraft:sofa_left_yellow4