gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_black2
give @s ghoulcraft:sofa_blue2
give @s ghoulcraft:sofa_brown2
give @s ghoulcraft:sofa_cyan2
give @s ghoulcraft:sofa_green2
give @s ghoulcraft:sofa_gray2
give @s ghoulcraft:sofa_lblue2
give @s ghoulcraft:sofa_lgray2
give @s ghoulcraft:sofa_lime2
give @s ghoulcraft:sofa_orange2
give @s ghoulcraft:sofa_magenta2
give @s ghoulcraft:sofa_pink2
give @s ghoulcraft:sofa_purple2
give @s ghoulcraft:sofa_red2
give @s ghoulcraft:sofa_white2
give @s ghoulcraft:sofa_yellow2