gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_corner_black3
give @s ghoulcraft:sofa_corner_blue3
give @s ghoulcraft:sofa_corner_brown3
give @s ghoulcraft:sofa_corner_cyan3
give @s ghoulcraft:sofa_corner_green3
give @s ghoulcraft:sofa_corner_gray3
give @s ghoulcraft:sofa_corner_lblue3
give @s ghoulcraft:sofa_corner_lgray3
give @s ghoulcraft:sofa_corner_lime3
give @s ghoulcraft:sofa_corner_orange3
give @s ghoulcraft:sofa_corner_magenta3
give @s ghoulcraft:sofa_corner_pink3
give @s ghoulcraft:sofa_corner_purple3
give @s ghoulcraft:sofa_corner_red3
give @s ghoulcraft:sofa_corner_white3
give @s ghoulcraft:sofa_corner_yellow3