gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_corner_black5
give @s ghoulcraft:sofa_corner_blue5
give @s ghoulcraft:sofa_corner_brown5
give @s ghoulcraft:sofa_corner_cyan5
give @s ghoulcraft:sofa_corner_green5
give @s ghoulcraft:sofa_corner_gray5
give @s ghoulcraft:sofa_corner_lblue5
give @s ghoulcraft:sofa_corner_lgray5
give @s ghoulcraft:sofa_corner_lime5
give @s ghoulcraft:sofa_corner_orange5
give @s ghoulcraft:sofa_corner_magenta5
give @s ghoulcraft:sofa_corner_pink5
give @s ghoulcraft:sofa_corner_purple5
give @s ghoulcraft:sofa_corner_red5
give @s ghoulcraft:sofa_corner_white5
give @s ghoulcraft:sofa_corner_yellow5