gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_black3
give @s ghoulcraft:sofa_blue3
give @s ghoulcraft:sofa_brown3
give @s ghoulcraft:sofa_cyan3
give @s ghoulcraft:sofa_green3
give @s ghoulcraft:sofa_gray3
give @s ghoulcraft:sofa_lblue3
give @s ghoulcraft:sofa_lgray3
give @s ghoulcraft:sofa_lime3
give @s ghoulcraft:sofa_orange3
give @s ghoulcraft:sofa_magenta3
give @s ghoulcraft:sofa_pink3
give @s ghoulcraft:sofa_purple3
give @s ghoulcraft:sofa_red3
give @s ghoulcraft:sofa_white3
give @s ghoulcraft:sofa_yellow3