gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_right_black4
give @s ghoulcraft:sofa_right_blue4
give @s ghoulcraft:sofa_right_brown4
give @s ghoulcraft:sofa_right_cyan4
give @s ghoulcraft:sofa_right_green4
give @s ghoulcraft:sofa_right_gray4
give @s ghoulcraft:sofa_right_lblue4
give @s ghoulcraft:sofa_right_lgray4
give @s ghoulcraft:sofa_right_lime4
give @s ghoulcraft:sofa_right_orange4
give @s ghoulcraft:sofa_right_magenta4
give @s ghoulcraft:sofa_right_pink4
give @s ghoulcraft:sofa_right_purple4
give @s ghoulcraft:sofa_right_red4
give @s ghoulcraft:sofa_right_white4
give @s ghoulcraft:sofa_right_yellow4