gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_corner_black2
give @s ghoulcraft:sofa_corner_blue2
give @s ghoulcraft:sofa_corner_brown2
give @s ghoulcraft:sofa_corner_cyan2
give @s ghoulcraft:sofa_corner_green2
give @s ghoulcraft:sofa_corner_gray2
give @s ghoulcraft:sofa_corner_lblue2
give @s ghoulcraft:sofa_corner_lgray2
give @s ghoulcraft:sofa_corner_lime2
give @s ghoulcraft:sofa_corner_orange2
give @s ghoulcraft:sofa_corner_magenta2
give @s ghoulcraft:sofa_corner_pink2
give @s ghoulcraft:sofa_corner_purple2
give @s ghoulcraft:sofa_corner_red2
give @s ghoulcraft:sofa_corner_white2
give @s ghoulcraft:sofa_corner_yellow2