gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_left_black5
give @s ghoulcraft:sofa_left_blue5
give @s ghoulcraft:sofa_left_brown5
give @s ghoulcraft:sofa_left_cyan5
give @s ghoulcraft:sofa_left_green5
give @s ghoulcraft:sofa_left_gray5
give @s ghoulcraft:sofa_left_lblue5
give @s ghoulcraft:sofa_left_lgray5
give @s ghoulcraft:sofa_left_lime5
give @s ghoulcraft:sofa_left_orange5
give @s ghoulcraft:sofa_left_magenta5
give @s ghoulcraft:sofa_left_pink5
give @s ghoulcraft:sofa_left_purple5
give @s ghoulcraft:sofa_left_red5
give @s ghoulcraft:sofa_left_white5
give @s ghoulcraft:sofa_left_yellow5