gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_mid_black2
give @s ghoulcraft:sofa_mid_blue2
give @s ghoulcraft:sofa_mid_brown2
give @s ghoulcraft:sofa_mid_cyan2
give @s ghoulcraft:sofa_mid_green2
give @s ghoulcraft:sofa_mid_gray2
give @s ghoulcraft:sofa_mid_lblue2
give @s ghoulcraft:sofa_mid_lgray2
give @s ghoulcraft:sofa_mid_lime2
give @s ghoulcraft:sofa_mid_orange2
give @s ghoulcraft:sofa_mid_magenta2
give @s ghoulcraft:sofa_mid_pink2
give @s ghoulcraft:sofa_mid_purple2
give @s ghoulcraft:sofa_mid_red2
give @s ghoulcraft:sofa_mid_white2
give @s ghoulcraft:sofa_mid_yellow2