gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_left_black6
give @s ghoulcraft:sofa_left_blue6
give @s ghoulcraft:sofa_left_brown6
give @s ghoulcraft:sofa_left_cyan6
give @s ghoulcraft:sofa_left_green6
give @s ghoulcraft:sofa_left_gray6
give @s ghoulcraft:sofa_left_lblue6
give @s ghoulcraft:sofa_left_lgray6
give @s ghoulcraft:sofa_left_lime6
give @s ghoulcraft:sofa_left_orange6
give @s ghoulcraft:sofa_left_magenta6
give @s ghoulcraft:sofa_left_pink6
give @s ghoulcraft:sofa_left_purple6
give @s ghoulcraft:sofa_left_red6
give @s ghoulcraft:sofa_left_white6
give @s ghoulcraft:sofa_left_yellow6