gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_right_black2
give @s ghoulcraft:sofa_right_blue2
give @s ghoulcraft:sofa_right_brown2
give @s ghoulcraft:sofa_right_cyan2
give @s ghoulcraft:sofa_right_green2
give @s ghoulcraft:sofa_right_gray2
give @s ghoulcraft:sofa_right_lblue2
give @s ghoulcraft:sofa_right_lgray2
give @s ghoulcraft:sofa_right_lime2
give @s ghoulcraft:sofa_right_orange2
give @s ghoulcraft:sofa_right_magenta2
give @s ghoulcraft:sofa_right_pink2
give @s ghoulcraft:sofa_right_purple2
give @s ghoulcraft:sofa_right_red2
give @s ghoulcraft:sofa_right_white2
give @s ghoulcraft:sofa_right_yellow2