gamerule sendcommandfeedback false
give @s ghoulcraft:windowseat_acacia_black
give @s ghoulcraft:windowseat_acacia_blue
give @s ghoulcraft:windowseat_acacia_brown
give @s ghoulcraft:windowseat_acacia_cyan
give @s ghoulcraft:windowseat_acacia_green
give @s ghoulcraft:windowseat_acacia_gray
give @s ghoulcraft:windowseat_acacia_light_blue
give @s ghoulcraft:windowseat_acacia_light_gray
give @s ghoulcraft:windowseat_acacia_lime
give @s ghoulcraft:windowseat_acacia_orange
give @s ghoulcraft:windowseat_acacia_magenta
give @s ghoulcraft:windowseat_acacia_pink
give @s ghoulcraft:windowseat_acacia_purple
give @s ghoulcraft:windowseat_acacia_red
give @s ghoulcraft:windowseat_acacia_white
give @s ghoulcraft:windowseat_acacia_yellow