gamerule sendcommandfeedback false
give @s ghoulcraft:windowseat_dark_black
give @s ghoulcraft:windowseat_dark_blue
give @s ghoulcraft:windowseat_dark_brown
give @s ghoulcraft:windowseat_dark_cyan
give @s ghoulcraft:windowseat_dark_green
give @s ghoulcraft:windowseat_dark_gray
give @s ghoulcraft:windowseat_dark_light_blue
give @s ghoulcraft:windowseat_dark_light_gray
give @s ghoulcraft:windowseat_dark_lime
give @s ghoulcraft:windowseat_dark_orange
give @s ghoulcraft:windowseat_dark_magenta
give @s ghoulcraft:windowseat_dark_pink
give @s ghoulcraft:windowseat_dark_purple
give @s ghoulcraft:windowseat_dark_red
give @s ghoulcraft:windowseat_dark_white
give @s ghoulcraft:windowseat_dark_yellow