gamerule sendcommandfeedback false
give @s ghoulcraft:canmatch_acacia_black
give @s ghoulcraft:canmatch_acacia_blue
give @s ghoulcraft:canmatch_acacia_brown
give @s ghoulcraft:canmatch_acacia_cyan
give @s ghoulcraft:canmatch_acacia_green
give @s ghoulcraft:canmatch_acacia_gray
give @s ghoulcraft:canmatch_acacia_light_blue
give @s ghoulcraft:canmatch_acacia_light_gray
give @s ghoulcraft:canmatch_acacia_lime
give @s ghoulcraft:canmatch_acacia_orange
give @s ghoulcraft:canmatch_acacia_magenta
give @s ghoulcraft:canmatch_acacia_pink
give @s ghoulcraft:canmatch_acacia_purple
give @s ghoulcraft:canmatch_acacia_red
give @s ghoulcraft:canmatch_acacia_white
give @s ghoulcraft:canmatch_acacia_yellow