gamerule sendcommandfeedback false
give @s ghoulcraft:canmatch_spruce_black
give @s ghoulcraft:canmatch_spruce_blue
give @s ghoulcraft:canmatch_spruce_brown
give @s ghoulcraft:canmatch_spruce_cyan
give @s ghoulcraft:canmatch_spruce_green
give @s ghoulcraft:canmatch_spruce_gray
give @s ghoulcraft:canmatch_spruce_light_blue
give @s ghoulcraft:canmatch_spruce_light_gray
give @s ghoulcraft:canmatch_spruce_lime
give @s ghoulcraft:canmatch_spruce_orange
give @s ghoulcraft:canmatch_spruce_magenta
give @s ghoulcraft:canmatch_spruce_pink
give @s ghoulcraft:canmatch_spruce_purple
give @s ghoulcraft:canmatch_spruce_red
give @s ghoulcraft:canmatch_spruce_white
give @s ghoulcraft:canmatch_spruce_yellow