gamerule sendcommandfeedback false
give @s ghoulcraft:canmatch_dark_black
give @s ghoulcraft:canmatch_dark_blue
give @s ghoulcraft:canmatch_dark_brown
give @s ghoulcraft:canmatch_dark_cyan
give @s ghoulcraft:canmatch_dark_green
give @s ghoulcraft:canmatch_dark_gray
give @s ghoulcraft:canmatch_dark_light_blue
give @s ghoulcraft:canmatch_dark_light_gray
give @s ghoulcraft:canmatch_dark_lime
give @s ghoulcraft:canmatch_dark_orange
give @s ghoulcraft:canmatch_dark_magenta
give @s ghoulcraft:canmatch_dark_pink
give @s ghoulcraft:canmatch_dark_purple
give @s ghoulcraft:canmatch_dark_red
give @s ghoulcraft:canmatch_dark_white
give @s ghoulcraft:canmatch_dark_yellow