gamerule sendcommandfeedback false
give @s ghoulcraft:crib_black
give @s ghoulcraft:crib_blue
give @s ghoulcraft:crib_brown
give @s ghoulcraft:crib_cyan
give @s ghoulcraft:crib_green
give @s ghoulcraft:crib_gray
give @s ghoulcraft:crib_lblue
give @s ghoulcraft:crib_lgray
give @s ghoulcraft:crib_lime
give @s ghoulcraft:crib_orange
give @s ghoulcraft:crib_magenta
give @s ghoulcraft:crib_pink
give @s ghoulcraft:crib_purple
give @s ghoulcraft:crib_red
give @s ghoulcraft:crib_white
give @s ghoulcraft:crib_yellow