gamerule sendcommandfeedback false
give @s ghoulcraft:bed_iron_black
give @s ghoulcraft:bed_iron_blue
give @s ghoulcraft:bed_iron_brown
give @s ghoulcraft:bed_iron_cyan
give @s ghoulcraft:bed_iron_green
give @s ghoulcraft:bed_iron_gray
give @s ghoulcraft:bed_iron_light_blue
give @s ghoulcraft:bed_iron_light_gray
give @s ghoulcraft:bed_iron_lime
give @s ghoulcraft:bed_iron_orange
give @s ghoulcraft:bed_iron_magenta
give @s ghoulcraft:bed_iron_pink
give @s ghoulcraft:bed_iron_purple
give @s ghoulcraft:bed_iron_red
give @s ghoulcraft:bed_iron_white
give @s ghoulcraft:bed_iron_yellow