gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_corner_black4
give @s ghoulcraft:sofa_corner_blue4
give @s ghoulcraft:sofa_corner_brown4
give @s ghoulcraft:sofa_corner_cyan4
give @s ghoulcraft:sofa_corner_green4
give @s ghoulcraft:sofa_corner_gray4
give @s ghoulcraft:sofa_corner_lblue4
give @s ghoulcraft:sofa_corner_lgray4
give @s ghoulcraft:sofa_corner_lime4
give @s ghoulcraft:sofa_corner_orange4
give @s ghoulcraft:sofa_corner_magenta4
give @s ghoulcraft:sofa_corner_pink4
give @s ghoulcraft:sofa_corner_purple4
give @s ghoulcraft:sofa_corner_red4
give @s ghoulcraft:sofa_corner_white4
give @s ghoulcraft:sofa_corner_yellow4