gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_corner_black6
give @s ghoulcraft:sofa_corner_blue6
give @s ghoulcraft:sofa_corner_brown6
give @s ghoulcraft:sofa_corner_cyan6
give @s ghoulcraft:sofa_corner_green6
give @s ghoulcraft:sofa_corner_gray6
give @s ghoulcraft:sofa_corner_lblue6
give @s ghoulcraft:sofa_corner_lgray6
give @s ghoulcraft:sofa_corner_lime6
give @s ghoulcraft:sofa_corner_orange6
give @s ghoulcraft:sofa_corner_magenta6
give @s ghoulcraft:sofa_corner_pink6
give @s ghoulcraft:sofa_corner_purple6
give @s ghoulcraft:sofa_corner_red6
give @s ghoulcraft:sofa_corner_white6
give @s ghoulcraft:sofa_corner_yellow6