gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_black6
give @s ghoulcraft:sofa_blue6
give @s ghoulcraft:sofa_brown6
give @s ghoulcraft:sofa_cyan6
give @s ghoulcraft:sofa_green6
give @s ghoulcraft:sofa_gray6
give @s ghoulcraft:sofa_lblue6
give @s ghoulcraft:sofa_lgray6
give @s ghoulcraft:sofa_lime6
give @s ghoulcraft:sofa_orange6
give @s ghoulcraft:sofa_magenta6
give @s ghoulcraft:sofa_pink6
give @s ghoulcraft:sofa_purple6
give @s ghoulcraft:sofa_red6
give @s ghoulcraft:sofa_white6
give @s ghoulcraft:sofa_yellow6