gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_right_black1
give @s ghoulcraft:sofa_right_blue1
give @s ghoulcraft:sofa_right_brown1
give @s ghoulcraft:sofa_right_cyan1
give @s ghoulcraft:sofa_right_green1
give @s ghoulcraft:sofa_right_gray1
give @s ghoulcraft:sofa_right_lblue1
give @s ghoulcraft:sofa_right_lgray1
give @s ghoulcraft:sofa_right_lime1
give @s ghoulcraft:sofa_right_orange1
give @s ghoulcraft:sofa_right_magenta1
give @s ghoulcraft:sofa_right_pink1
give @s ghoulcraft:sofa_right_purple1
give @s ghoulcraft:sofa_right_red1
give @s ghoulcraft:sofa_right_white1
give @s ghoulcraft:sofa_right_yellow1