gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_mid_black3
give @s ghoulcraft:sofa_mid_blue3
give @s ghoulcraft:sofa_mid_brown3
give @s ghoulcraft:sofa_mid_cyan3
give @s ghoulcraft:sofa_mid_green3
give @s ghoulcraft:sofa_mid_gray3
give @s ghoulcraft:sofa_mid_lblue3
give @s ghoulcraft:sofa_mid_lgray3
give @s ghoulcraft:sofa_mid_lime3
give @s ghoulcraft:sofa_mid_orange3
give @s ghoulcraft:sofa_mid_magenta3
give @s ghoulcraft:sofa_mid_pink3
give @s ghoulcraft:sofa_mid_purple3
give @s ghoulcraft:sofa_mid_red3
give @s ghoulcraft:sofa_mid_white3
give @s ghoulcraft:sofa_mid_yellow3