gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_mid_black1
give @s ghoulcraft:sofa_mid_blue1
give @s ghoulcraft:sofa_mid_brown1
give @s ghoulcraft:sofa_mid_cyan1
give @s ghoulcraft:sofa_mid_green1
give @s ghoulcraft:sofa_mid_gray1
give @s ghoulcraft:sofa_mid_lblue1
give @s ghoulcraft:sofa_mid_lgray1
give @s ghoulcraft:sofa_mid_lime1
give @s ghoulcraft:sofa_mid_orange1
give @s ghoulcraft:sofa_mid_magenta1
give @s ghoulcraft:sofa_mid_pink1
give @s ghoulcraft:sofa_mid_purple1
give @s ghoulcraft:sofa_mid_red1
give @s ghoulcraft:sofa_mid_white1
give @s ghoulcraft:sofa_mid_yellow1