gamerule sendcommandfeedback false
give @s ghoulcraft:sofa_mid_black4
give @s ghoulcraft:sofa_mid_blue4
give @s ghoulcraft:sofa_mid_brown4
give @s ghoulcraft:sofa_mid_cyan4
give @s ghoulcraft:sofa_mid_green4
give @s ghoulcraft:sofa_mid_gray4
give @s ghoulcraft:sofa_mid_lblue4
give @s ghoulcraft:sofa_mid_lgray4
give @s ghoulcraft:sofa_mid_lime4
give @s ghoulcraft:sofa_mid_orange4
give @s ghoulcraft:sofa_mid_magenta4
give @s ghoulcraft:sofa_mid_pink4
give @s ghoulcraft:sofa_mid_purple4
give @s ghoulcraft:sofa_mid_red4
give @s ghoulcraft:sofa_mid_white4
give @s ghoulcraft:sofa_mid_yellow4