gamerule sendcommandfeedback false
give @s ghoulcraft:windowseat_jungle_black
give @s ghoulcraft:windowseat_jungle_blue
give @s ghoulcraft:windowseat_jungle_brown
give @s ghoulcraft:windowseat_jungle_cyan
give @s ghoulcraft:windowseat_jungle_green
give @s ghoulcraft:windowseat_jungle_gray
give @s ghoulcraft:windowseat_jungle_light_blue
give @s ghoulcraft:windowseat_jungle_light_gray
give @s ghoulcraft:windowseat_jungle_lime
give @s ghoulcraft:windowseat_jungle_orange
give @s ghoulcraft:windowseat_jungle_magenta
give @s ghoulcraft:windowseat_jungle_pink
give @s ghoulcraft:windowseat_jungle_purple
give @s ghoulcraft:windowseat_jungle_red
give @s ghoulcraft:windowseat_jungle_white
give @s ghoulcraft:windowseat_jungle_yellow