gamerule sendcommandfeedback false
give @s ghoulcraft:windowseat_spruce_black
give @s ghoulcraft:windowseat_spruce_blue
give @s ghoulcraft:windowseat_spruce_brown
give @s ghoulcraft:windowseat_spruce_cyan
give @s ghoulcraft:windowseat_spruce_green
give @s ghoulcraft:windowseat_spruce_gray
give @s ghoulcraft:windowseat_spruce_light_blue
give @s ghoulcraft:windowseat_spruce_light_gray
give @s ghoulcraft:windowseat_spruce_lime
give @s ghoulcraft:windowseat_spruce_orange
give @s ghoulcraft:windowseat_spruce_magenta
give @s ghoulcraft:windowseat_spruce_pink
give @s ghoulcraft:windowseat_spruce_purple
give @s ghoulcraft:windowseat_spruce_red
give @s ghoulcraft:windowseat_spruce_white
give @s ghoulcraft:windowseat_spruce_yellow